Rocky step9 アプリの各種設定
rocky-tanaka/training pull request #7
Opened 2021-05-17 02:41 UTC by rocky-tanaka

## 概要
アプリケーションの言語、エラー設定

## 実装内容
- i18n化
- public下にある404.htmlと500.htmlを編集

## プレビュー

### 404
<img width="1792" alt="Screen Shot 2021-05-17 at 11 25 19" src="https://user-images.githubusercontent.com/83940783/118425484-3b71d480-b704-11eb-9cba-48c40414b101.png">

### 500
<img width="1792" alt="Screen Shot 2021-05-17 at 11 26 02" src="https://user-images.githubusercontent.com/83940783/118425493-42004c00-b704-11eb-9c54-58f3fb02dd12.png">

2021-05-17 02:42 UTC, rocky-tanaka commented on tanask/app/controllers/tasks_controller.rb
> +      flash[:danger] = t('flash.update.danger')
i18n化してメッセージが言語環境によって変わるように

2021-05-17 02:43 UTC, rocky-tanaka commented on tanask/app/views/tasks/new.html.erb
> +    <h1><%= t '.title'%></h1>
ページタイトルもi18n化

2021-05-17 02:44 UTC, rocky-tanaka commented on tanask/public/404.html
> +    <p>If you are the application owner check the logs for more information. Go back to <a href="/">TOP</a> page.</p>
TOPページに戻れるようにリンクを追加

2021-05-17 07:11 UTC, craftzcat reviewed
今回の変更差分について気になった点をコメントしました！
ちょっとこのStepの説明文があまり良くないのです申し訳ないのですが、
エラーページの表示は以下のように表示の出し分けができるようエラーハンドリングをしてみてください。

| 開発環境 | 本番、テスト環境、他 |
| --- | --- |
| <img width="500" src="https://user-images.githubusercontent.com/32451781/118446154-42abd900-b72a-11eb-846c-d2c720f2bd30.png"> | <img width="600" src="https://user-images.githubusercontent.com/32451781/118445822-dfba4200-b729-11eb-950a-b9d02e31e2b4.png"> |

2021-05-17 07:11 UTC, craftzcat commented on tanask/app/models/task.rb
> +  validates :name, presence: true
【FYI（修正任意）】
しっかりタスク名のバリデーションを追加していていいですね:thumbsup:
ただ、この状態だと文字数が1~255文字まで入力できてしまうので、長さに関してもバリデーションを追加したほうが良いかと思いますー

個人的な意見なので修正は任意です:bow:

2021-05-17 07:14 UTC, craftzcat commented on tanask/app/controllers/tasks_controller.rb
> +      flash[:danger] = t('flash.update.danger')
ハードコーディングが少なくていい感じです〜
英語の翻訳ファイルも書いてくださったんですね。
英語はマストではないので必要ないと感じたらスキップでお願いします:bow:

2021-05-18 03:47 UTC, craftzcat commented on tanask/app/controllers/concerns/error_handlers.rb
> +end
末尾に改行をお願いします！
POSIX上、テキストファイルは以下の概念で扱われるので末尾の改行が必要になります。

- テキストファイルは「行」の集合体
-「行」は「0文字以上の文字+改行」から構成される

忘れがちなのでエディタ、IDEの設定で自動で改行するようにすると楽です〜

2021-05-18 03:47 UTC, craftzcat commented on tanask/config/locales/en.yml
> +      danger:  'Failed to create the task'
【追記】
モデルが増えた際に、

```yml
  flash:
    create:
      success: "The #{model} is successfully created!"
      danger:  "Failed to create the #{model}"
```

に変更して、呼び出しを

```ruby
t 'flash.create.success', :name => 'task'
```

みたいな感じにするのならそもままでも良さそうですー

2021-05-18 06:49 UTC, rocky-tanaka commented on tanask/app/controllers/concerns/error_handlers.rb
> +end
様々なファイルに改行を追加しました！

2021-05-18 06:50 UTC, rocky-tanaka commented on tanask/spec/system/tasks_controller.rb
> +    it 'can see Task List' do
テストケースの作成やcontext, itの使い分けについて修正しました。

2021-05-18 06:51 UTC, rocky-tanaka commented on tanask/spec/system/tasks_controller.rb
> +    end
FactoryBotを使うように修正しました。

2021-05-18 06:53 UTC, rocky-tanaka commented on tanask/public/404.html
> +       width="600">
ApplicationControllerでエラーページが出るように修正しました。

2021-05-18 06:53 UTC, rocky-tanaka commented on tanask/config/environments/development.rb
> +  config.consider_all_requests_local = false
develop環境でエラーページを見るために設定していましたが、
test及びproduction 環境のみでエラーページが出るように修正しました。

2021-05-18 06:54 UTC, rocky-tanaka commented on tanask/app/views/layouts/_form.html.erb
> +  <p><%= f.submit 'SUBMIT' %></p>
ボタンの文字列もi18n化しました。

2021-05-18 06:55 UTC, rocky-tanaka commented on tanask/config/locales/en.yml
> +      danger:  'Failed to create the task'
上の方法でやってみます！

2021-05-18 06:56 UTC, rocky-tanaka commented on tanask/app/controllers/tasks_controller.rb
> +    @task = Task.find_by(params[:id])
IDEの補完で`find_by`になっていました…
findを利用するように修正しました。

2021-05-18 06:57 UTC, rocky-tanaka commented on tanask/app/models/task.rb
> +  validates :name, presence: true
文字数を50文字までに制限しました。

2021-05-18 08:59 UTC, merged

2021-05-18 09:24 UTC, craftzcat requested changes
@rocky-tanaka 
いくつか気になった点、いい実装だなと思った点をコメントしましたー！

2021-05-18 09:24 UTC, craftzcat commented on tanask/spec/system/tasks_controller_spec.rb
> +  let!(:task2) { create(:task_template, name: 'test_name2', description: 'test_description2') }
ここに`let!`で書いてしまうと、全てのテストケースで上記2件のテスト用のデータが作成されてしまうのでパフォーマンス的に良くないです。。
（ラクマ内だと何千ものテストケースがあるので開発効率を考慮するとパフォーマンスは結構大事）

そのテストデータが必要な`context`内に書くか、まとめたい場合は`shared_context`とかにまとめて書くのが良さそうです〜

shared_contextについてのDocs:：https://relishapp.com/rspec/rspec-core/docs/example-groups/shared-context
ブログ記事：https://chaika.hatenablog.com/entry/2019/05/31/083000

2021-05-18 09:24 UTC, craftzcat commented on tanask/spec/system/tasks_controller_spec.rb
> +  let!(:task2) { create(:task_template, name: 'test_name2', description: 'test_description2') }
ちなみにRockyさんご存知かもしれないですけど、`let`とかくと挙動が若干変わります〜
※ 余裕があれば調べてみてください〜
https://www.ryotaku.com/entry/2019/09/10/000000

2021-05-18 09:24 UTC, craftzcat commented on tanask/app/controllers/tasks_controller.rb
> +      flash[:danger] = t('flash.tasks.create.danger')
この書き方だとflashメッセージが表示されないですね:thinking:
「render redirect_to flash」とかでググってみると良い方法が見つかりそうです〜

2021-05-18 09:24 UTC, craftzcat commented on tanask/app/controllers/tasks_controller.rb
>      redirect_to @task # make GET method
`@task.destory`が失敗したときのエラーハンドリングも必要なので`new`メソッドや`update`メソッド同様に追加しましょう〜

2021-05-18 09:24 UTC, craftzcat commented on tanask/app/controllers/concerns/error_handlers.rb
> +    rescue_from Exception, with: :rescue500
`Exception`で定義するのは良くないです〜
というのも`Exception`は全てのRailsにおける全ての例外の親クラスです。
https://docs.ruby-lang.org/ja/latest/class/Exception.html

なのでrescureするスコープがちょっと広いです〜
Railsアプリで発生する例外という意味では`StandardError`を使いましょう
https://docs.ruby-lang.org/ja/latest/class/StandardError.html

---

たぶんRockyさんが見つけたこの記事（[[Rails 4.x] エラーページの作り方](https://qiita.com/colorrabbit/items/88815b94f63608a801a8)）の内容からもってきたと思うのですが、Qiitaの情報は細かい部分が間違っていることが多いので、コードを読んで理解できたら写すぐらいの感じで使いましょう〜

2021-05-18 10:03 UTC, rocky-tanaka commented on tanask/config/routes.rb
> +  # for error (un exist URL)
修正しました。

2021-05-18 10:04 UTC, rocky-tanaka commented on tanask/app/controllers/application_controller.rb
> +  include ErrorHandlers if Rails.env.production? || Rails.env.staging? || Rails.env.test?
参考にしたページ通りに記述していたので、Stagingが生まれていました。
`include ErrorHandlers unless Rails.env.development?`の表記に変更しました。

2021-05-18 10:04 UTC, rocky-tanaka commented on tanask/app/controllers/concerns/error_handlers.rb
> +    @exception = error
呼び出していないので削除しても良いでしょうか？

2021-05-18 10:04 UTC, rocky-tanaka commented on tanask/app/controllers/tasks_controller.rb
> +    # raise # FOR DEBUG!! 500 error
コメント削除しました。

2021-05-18 10:05 UTC, rocky-tanaka commented on tanask/app/controllers/tasks_controller.rb
> +    # p @task.name
コメント削除しました。

2021-05-18 10:06 UTC, rocky-tanaka commented on tanask/app/controllers/tasks_controller.rb
>        # GET -> tasks/:id -> tasks/show?
クラスとインスタンスの違いがまだわかってないのでちょっと勉強してきます！！！

2021-05-18 10:07 UTC, rocky-tanaka commented on tanask/config/locales/views/tasks/en.yml
> +      button: 'submit'
改行を追加しました。

2021-05-18 10:07 UTC, rocky-tanaka commented on tanask/config/locales/views/tasks/ja.yml
> +      button: '提出'
改行を追加しました。

2021-05-18 10:08 UTC, rocky-tanaka commented on tanask/spec/factories/tasks.rb
> +end
改行を追加しました。

2021-05-18 10:08 UTC, rocky-tanaka commented on tanask/app/controllers/tasks_controller.rb
> +    #     # p "#{params[:id]}"
コメント消しました！

2021-05-18 10:15 UTC, rocky-tanaka commented on tanask/app/controllers/tasks_controller.rb
> +      flash[:danger] = t('flash.tasks.create.danger')
僕の環境だとflashメッセージが表示されるのですが、
<img width="308" alt="Screen Shot 2021-05-18 at 19 14 14" src="https://user-images.githubusercontent.com/83940783/118634232-45cbc580-b80d-11eb-8e06-4227ae530738.png">


`render`と`flash.now`を利用したほうがいいということでしょうか？

2021-05-18 10:20 UTC, rocky-tanaka commented on tanask/app/controllers/concerns/error_handlers.rb
> +    rescue_from Exception, with: :rescue500
StandardErrorを利用するように変更しました。

2021-05-18 10:21 UTC, rocky-tanaka commented on tanask/app/controllers/concerns/error_handlers.rb
> +    @exception = error
コメントアウトしても問題なく動作したため削除しました。

2021-05-21 01:00 UTC, craftzcat commented on tanask/app/controllers/tasks_controller.rb
> +      flash[:danger] = t('flash.tasks.create.danger')
あれ、なんでだろう、普通はでないはずなんですが:thinking:
はい、それでお願いします:pray: